### ISSUE TITLE
Setup doesn't continue

### ISSUE THREAD

**Issue by Gensokian** [crater-invoice/crater#830]
**Describe the bug**
I am trying to install crater, but cannot create the database connection.
When trying to set my dockerized version up, I cannot get past the database setup, as it always runs into "Error something went wrong". When reloading the page and trying to run the setup again.

**Expected behavior**
The setup continues as expected

**Screenshots**
When freshly set up:
![image](https://user-images.githubusercontent.com/9213561/157181079-3592526d-b93e-4b7d-a09d-9d387a3c63c4.png)

Reloading after “connecting”
![image](https://user-images.githubusercontent.com/9213561/157180563-2d9d5dea-9a14-4aeb-bb1c-9c58ecc5c502.png)

**Please complete the following information:**
- Crater version: 6.0.6 (Latest from GIT)
- PHP version: 7.4-fpm
- Database type and version: Postgres (latest) OR MySQL (the latest MariaDB),

**Optional info**
- OS:  Windows, Server runs on Linux
- Browser: Chrome – Vivaldi
- Changes: I added the following code to the Dockerfile to allow the PostgreSQL PHP extension to work, since I thought it might have been a bug in the MySQL Connection. It apparently wasn't. :)

```# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql```

**Comment by mohitpanjwani** [comment]
> 

Hey, can you enable `APP_DEBUG=true` on .env file and then retry? 

Also what value are you trying to enter for `DB_HOST`, by default it should just be `db` unless you've updated the docker-compose file yourself.

**Comment by Gensokian** [comment]
# docker-compose.yml
```yml
version: '3'

services:
  app:
    build:
      args:
        user: crater-user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: crater-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker-compose/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:rw,delegated
    networks:
      - crater

  database:
    image: mysql
    restart: always
    volumes:
      - ./mysqldb:/var/lib/mysql
      # If you want to persist data on the host, comment the line above this one...
      # and uncomment the line under this one.
      #- ./docker-compose/db/data:/var/lib/mysql:rw,delegated
    environment:
      MYSQL_USER: crater
      MYSQL_PASSWORD: crater
      MYSQL_DATABASE: crater
      MYSQL_ROOT_PASSWORD: crater
    ports:
      - '33006:3306'
    networks:
      - crater

  nginx:
    image: nginx:1.17-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - crater

  postgres:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=[EDITED]
      - POSTGRES_DB=crater
      - APP_DB_USER=crater
      - APP_DB_PASS=[EDITED]
      - APP_DB_NAME=crater
    volumes:
      - ./pgdb:/docker-entrypoint-initdb.d/
    ports:
      - 2345:5432
    networks:
      - crater


  cron:
    build:
      context: ./
      dockerfile: ./docker-compose/cron.dockerfile
    volumes:
      - ./:/var/www
    networks:
      - crater

networks:
  crater:
    driver: bridge```
 

# Dockerfile
```
FROM php:7.4-fpm

# Arguments defined in docker-compose.yml
ARG user
ARG uid

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    libmagickwand-dev \
    mariadb-client

#PHPFIX
RUN apt-get update

# Install Postgre PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
    && docker-php-ext-install pdo pdo_pgsql pgsql


# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pecl install imagick \
    && docker-php-ext-enable imagick

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl bcmath gd

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN useradd -G www-data,root -u $uid -d /home/$user $user
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www

USER $user```

# Env
```
APP_ENV=production
APP_KEY=base64:XiyXfbehZzYdiLRI88UgEkHmkB4tuvxtNO2DdGUBYdw=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=https://money.james-things.com

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_PORT=5432
DB_DATABASE=crater
DB_USERNAME=[EDITED]
DB_PASSWORD="[EDITED]"

# Also tried with
# DB_CONNECTION=mysql
# DB_HOST=database
# DB_PORT=3306
# DB_DATABASE=crater
# DB_USERNAME=crater
# DB_PASSWORD="crater"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_DRIVER=sync
SESSION_DRIVER=cookie
SESSION_LIFETIME=1440

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=[EDITED]
MAIL_PORT=[EDITED]
MAIL_USERNAME=[EDITED]
MAIL_PASSWORD=[EDITED]
MAIL_ENCRYPTION=[EDITED]
```

Funny thing is; Crater seems to connect well with both, postgres AND mysql;
(Example Mysql)
![image](https://user-images.githubusercontent.com/9213561/157238708-55b28797-f900-4d16-8431-08503c69f534.png)
